rails/config/routes.rb
Rails.application.routes.draw do
  get "about/index"
  resources :posts
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  namespace :turbo do
    namespace :ios do
      resource :path_configuration, only: :show
    end
    # namespace :android do
    #   resource :path_configuration, only: :show
    # end
  end

  # Defines the root path route ("/")
  root "posts#index"
end

rails/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

rails/app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  validates :title, :body, presence: true
end

rails/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
end

rails/app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def authenticate_user!
    redirect_to root_path, notice: "You must login" unless user_signed_in?
  end
end

rails/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[show index]

  def index
    @posts = Post.all
  end

  def show
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params.merge(user: current_user))

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

rails/app/controllers/turbo/ios/path_configurations_controller.rb
# http://localhost:3000/turbo/ios/path_configuration

module Turbo
  module Ios
    class PathConfigurationsController < ActionController::Base
      def show
        render json: {
            settings: {},
            rules: [
              {
                patterns: [
                  "/new$",
                  "/edit$",
                  "/users/sign_in"
                ],
                properties: {
                  context: "modal"
                }
              }
            ]
          }
      end
    end
  end
end

rails/app/helpers/about_helper.rb
module AboutHelper
end

rails/app/helpers/application_helper.rb
module ApplicationHelper
end

rails/app/helpers/posts_helper.rb
module PostsHelper
end

rails/app/views/about/index.html.erb
<%= render partial: 'layouts/header', locals: { title: 'About', subtitle: 'Life, the universe and everything.' } %>

<p>Across the centuries not a sunrise but a galaxyrise descended from astronomers with pretty stories for which there's little good evidence a very small stage in a vast cosmic arena radio telescope? Something incredible is waiting to be known emerged into consciousness a mote of dust suspended in a sunbeam tingling of the spine from which we spring permanence of the stars. Extraplanetary at the edge of forever network of wormholes shores of the cosmic ocean inconspicuous motes of rock and gas take root and flourish and billions upon billions upon billions upon billions upon billions upon billions upon billions.</p>

<p>Rich in mystery something incredible is waiting to be known a mote of dust suspended in a sunbeam courage of our questions Sea of Tranquility circumnavigated? From which we spring kindling the energy hidden in matter white dwarf cosmos muse about intelligent beings. From which we spring intelligent beings not a sunrise but a galaxyrise realm of the galaxies extraordinary claims require extraordinary evidence intelligent beings? Across the centuries citizens of distant epochs made in the interiors of collapsing stars courage of our questions network of wormholes with pretty stories for which there's little good evidence and billions upon billions upon billions upon billions upon billions upon billions upon billions.</p>

rails/app/views/layouts/_header.html.erb
<header>
  <%= render partial: 'layouts/nav' %>
  <h1><%= title %></h1>
  <p><%= subtitle %></p>
</header>

rails/app/views/layouts/_nav.html.erb
<nav>
  <%= link_to 'Home', posts_path %>
  <%= link_to 'About', about_index_path %>
  <% if current_user %>
    <%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete } %>
  <% else %>
    <%= link_to 'Log In', new_user_session_path %>
  <% end %>
</nav>

rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <% flash.each do |type, msg| %>
      <div class="alert alert-info">
        <%= msg %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

rails/app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

rails/app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= post.body %>
  </p>

</div>

rails/app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= button_to "Delete", @post, method: :delete, class: 'turbo-native-hidden', "data-controller": "bridge--button" %>
  <%= link_to "Back to posts", posts_path %>
</div>

rails/app/views/posts/index.html.erb
<%= render partial: 'layouts/header', locals: { title: 'Simple Blog', subtitle: 'Life, the universe and everything' } %>

<div id="posts">
  <% @posts.each do |post| %>
    <p>
      <%= link_to post.title, post, class: 'post-link' %>
    </p>
    <p>
      <%= post.body.truncate(150, :omission => "...") %>
    </p>
  <% end %>
</div>

<p>
  <%= link_to "New post &#8594;".html_safe, new_post_path if current_user %>
</p>

rails/app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Cancel".html_safe, posts_path, class: 'button' %>
</div>

rails/app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Edit", edit_post_path(@post), class: 'turbo-native-hidden', "data-controller": "bridge--button" %>

  <%= link_to "Back to posts", posts_path, class: 'turbo-native-hidden' %>

</div>